### ISSUE TITLE
docker failure 

### ISSUE THREAD

**Issue by ghost** [Miouyouyou/armbian-desktop#27]
Fetched 769 MB in 21s (36.6 MB/s)
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/arm64/containerd.io_1.3.7-1_arm64.deb  Reading from proxy failed - read (115: Operation now in progress) [IP: ::1 3142]
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/arm64/docker-ce-cli_19.03.13~3-0~ubuntu-focal_arm64.deb  Reading from proxy failed - read (115: Operation now in progress) [IP: ::1 3142]
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/arm64/docker-ce_19.03.13~3-0~ubuntu-focal_arm64.deb  Reading from proxy failed - read (115: Operation now in progress) [IP: ::1 3142]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[ error ] ERROR in function create_rootfs_cache [ debootstrap.sh:255 ]
[ error ] Installation of Armbian packages failed

**Comment by Miouyouyou** [comment]
Yeah, docker will need to be removed, since it's an AARCH64 only package, and not really a "Desktop app" anyway.

That said... the reported problem here comes from the proxy setup used during the build, as stated in the error message.

If you click any of this link, you'll see that they're valid.
