### ISSUE TITLE
img file output naming 

### ISSUE THREAD

**Issue by ghost** [Miouyouyou/armbian-desktop#6]
Armbian_20.08.0-trunk_Pinebook-pro_focal_current_5.7.19_desktop.img.xz should add in the desktop name like Armbian_20.08.0-trunk_Pinebook-pro_focal_current_5.7.19_budgie_desktop.img.xz

**Comment by ghost** [comment]
patch done Armbian_20.08.0-trunk_Odroidn2_focal_current_5.8.12_dde_desktop.img

**Comment by ghost** [comment]
fixed

**Comment by Miouyouyou** [comment]
Alright !
